runtime: python27
threadsafe: true

handlers:
- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /static
  static_dir: static

- url: /
  script: main.app
  secure: always

- url: /.*
  script: main.app
  secure: always

libraries:
- name: flask
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: 2.7.11
- name: six
  version: latest

skip_files:
- ^(.*/)?.*\.py[co]$
- ^\.git$
- ^(.*/)?.*\.sh$